#!/usr/bin/env php

<?php
date_default_timezone_set('Asia/Shanghai');
define('ANTMAN_START', microtime(true));
define('ANTMAN_PATH', __DIR__);

require __DIR__.'/vendor/autoload.php';


$app = new Symfony\Component\Console\Application();

// register commands
$app->add(new Antman\Commands\JobListCommand());
$app->add(new Antman\Commands\JobStartCommand());
$app->add(new Antman\Commands\JobStopCommand());
$app->add(new Antman\Commands\WorkerStartCommand());

$app->run();
